"""empty message

Revision ID: 92ed9d8e14e4
Revises: 
Create Date: 2019-04-10 09:45:00.130401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ed9d8e14e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('fname', sa.String(length=75), nullable=False),
    sa.Column('lname', sa.String(length=75), nullable=True),
    sa.Column('roll', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verify', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('verify')
    )
    op.create_index(op.f('ix_user_roll'), 'user', ['roll'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roll'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
